// Code generated by protoc-gen-go. DO NOT EDIT.
// source: error.proto

package grpcerr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Code                 uint32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Temporary            bool       `protobuf:"varint,3,opt,name=temporary,proto3" json:"temporary,omitempty"`
	ErrCode              uint32     `protobuf:"varint,4,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	Detail               []*any.Any `protobuf:"bytes,5,rep,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_error_b67d6bfaedc8c1bf, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetTemporary() bool {
	if m != nil {
		return m.Temporary
	}
	return false
}

func (m *Error) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Error) GetDetail() []*any.Any {
	if m != nil {
		return m.Detail
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "grpcerr.Error")
}

func init() { proto.RegisterFile("error.proto", fileDescriptor_error_b67d6bfaedc8c1bf) }

var fileDescriptor_error_b67d6bfaedc8c1bf = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x4d, 0xaa, 0x83, 0x30,
	0x14, 0x85, 0xc9, 0xf3, 0x3f, 0xf2, 0x26, 0xe1, 0x0d, 0xe2, 0xa3, 0x83, 0xd0, 0x51, 0x06, 0x25,
	0x42, 0xbb, 0x82, 0x52, 0xba, 0x81, 0x6c, 0xa0, 0x44, 0xbd, 0x0d, 0x05, 0x35, 0x72, 0xb5, 0x03,
	0xf7, 0xd2, 0xc5, 0x16, 0x63, 0xa5, 0xb3, 0x7b, 0x3f, 0xce, 0xf9, 0x38, 0x34, 0x07, 0x44, 0x87,
	0x6a, 0x40, 0x37, 0x39, 0x96, 0x58, 0x1c, 0x6a, 0x40, 0xfc, 0x2f, 0xac, 0x73, 0xb6, 0x85, 0xd2,
	0xe3, 0xea, 0x79, 0x2f, 0x4d, 0x3f, 0xaf, 0x99, 0xfd, 0x8b, 0xd0, 0xe8, 0xba, 0x74, 0x18, 0xa3,
	0x61, 0xed, 0x1a, 0xe0, 0x44, 0x10, 0xf9, 0xab, 0xfd, 0xcd, 0x38, 0x4d, 0x3a, 0x18, 0x47, 0x63,
	0x81, 0xff, 0x08, 0x22, 0x33, 0xbd, 0xbd, 0x6c, 0x47, 0xb3, 0x09, 0xba, 0xc1, 0xa1, 0xc1, 0x99,
	0x07, 0x82, 0xc8, 0x54, 0x7f, 0x01, 0x2b, 0x68, 0x0a, 0x88, 0x37, 0xef, 0x0b, 0xbd, 0x2f, 0x01,
	0xc4, 0xcb, 0xa2, 0x3c, 0xd0, 0xb8, 0x81, 0xc9, 0x3c, 0x5a, 0x1e, 0x89, 0x40, 0xe6, 0xc7, 0x3f,
	0xb5, 0x8e, 0x53, 0xdb, 0x38, 0x75, 0xee, 0x67, 0xfd, 0xc9, 0x54, 0xb1, 0xa7, 0xa7, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x1b, 0x47, 0xb0, 0xa8, 0xd8, 0x00, 0x00, 0x00,
}
